// Code generated by bingoctl. DO NOT EDIT.
package main

import (
	"fmt"
	"os"

	_ "{{.MigrationImport}}"

	"github.com/bingo-project/bingoctl/pkg/db"
	"github.com/bingo-project/bingoctl/pkg/migrate"
	"github.com/spf13/pflag"
)

func main() {
	var (
		host     string
		username string
		password string
		database string
		table    string
	)

	pflag.StringVar(&host, "host", "", "database host")
	pflag.StringVar(&username, "username", "", "database username")
	pflag.StringVar(&password, "password", "", "database password")
	pflag.StringVar(&database, "database", "", "database name")
	pflag.StringVar(&table, "table", migrate.DefaultTableName, "migration table name")
	pflag.Parse()

	args := pflag.Args()
	if len(args) < 1 {
		fmt.Println("Usage: migrator <up|rollback|reset|refresh|fresh> --host=<host> --username=<user> --password=<pass> --database=<db> [--table=<table>]")
		os.Exit(1)
	}

	dbConn, err := db.NewMySQL(&db.MySQLOptions{
		Host:     host,
		Username: username,
		Password: password,
		Database: database,
	})
	if err != nil {
		fmt.Printf("Failed to connect database: %v\n", err)
		os.Exit(1)
	}

	migrator := migrate.NewMigratorWithTable(dbConn, table)

	switch args[0] {
	case "up":
		migrator.Up()
	case "rollback":
		migrator.Rollback()
	case "reset":
		migrator.Reset()
	case "refresh":
		migrator.Refresh()
	case "fresh":
		migrator.Fresh()
	default:
		fmt.Printf("Unknown command: %s\n", args[0])
		os.Exit(1)
	}
}
