// Code generated by bingoctl. DO NOT EDIT.
package main

import (
	"fmt"
	"os"

	"{{.SeederImport}}"

	"github.com/bingo-project/bingoctl/pkg/db"
	"github.com/spf13/pflag"
)

func main() {
	var (
		host     string
		username string
		password string
		database string
		seederName string
	)

	pflag.StringVar(&host, "host", "", "database host")
	pflag.StringVar(&username, "username", "", "database username")
	pflag.StringVar(&password, "password", "", "database password")
	pflag.StringVar(&database, "database", "", "database name")
	pflag.StringVar(&seederName, "seeder", "", "specific seeder to run")
	pflag.Parse()

	// Connect to database
	dbConn, err := db.NewMySQL(&db.MySQLOptions{
		Host:     host,
		Username: username,
		Password: password,
		Database: database,
	})
	if err != nil {
		fmt.Printf("Failed to connect database: %v\n", err)
		os.Exit(1)
	}

	// Initialize seeder with database connection
	seeder.Init(dbConn)

	// Run seeders
	if err := seeder.RunSeeders(seederName); err != nil {
		fmt.Printf("Seeder failed: %v\n", err)
		os.Exit(1)
	}
}
