networks:
  {[.AppName]}:
    driver: bridge

services:
  apiserver:
    image: ${REGISTRY_PREFIX}/${APP_NAME}-apiserver:${APP_VERSION}
    container_name: ${APP_NAME}-apiserver
    restart: always
    platform: ${IMAGE_PLATFORM}
    build:
      context: ../../
      dockerfile: build/docker/{[.AppName]}-apiserver/Dockerfile
    networks:
      - {[.AppName]}
    ports:
      - '${APP_PORT}:8080'
      - '${GRPC_PORT}:8081'
    volumes:
      - ${DATA_PATH_HOST}/config:/etc/{[.AppName]}
      - ${DATA_PATH_HOST}/data/{[.AppName]}:/opt/{[.AppName]}/storage/public
      - ${DATA_PATH_HOST}/log/apiserver:/opt/{[.AppName]}/storage/log

  watcher:
    image: ${REGISTRY_PREFIX}/${APP_NAME}-watcher:${APP_VERSION}
    container_name: ${APP_NAME}-watcher
    restart: always
    platform: ${IMAGE_PLATFORM}
    build:
      context: ../../
      dockerfile: build/docker/{[.AppName]}-watcher/Dockerfile
    networks:
      - {[.AppName]}
    volumes:
      - ${DATA_PATH_HOST}/config:/etc/{[.AppName]}
      - ${DATA_PATH_HOST}/log/watcher:/opt/{[.AppName]}/storage/log

  bot:
    image: ${REGISTRY_PREFIX}/${APP_NAME}-bot:${APP_VERSION}
    container_name: ${APP_NAME}-bot
    restart: always
    platform: ${IMAGE_PLATFORM}
    build:
      context: ../../
      dockerfile: build/docker/{[.AppName]}-bot/Dockerfile
    networks:
      - {[.AppName]}
    volumes:
      - ${DATA_PATH_HOST}/config:/etc/{[.AppName]}
      - ${DATA_PATH_HOST}/log/bot:/opt/{[.AppName]}/storage/log

  # add alias to zsh to run {[.AppName]}ctl cmd.
  # alias {[.AppName]}ctl="docker run --rm -v /opt/{[.AppName]}/config:/etc/{[.AppName]} --network {[.AppName]}_{[.AppName]} {[.AppName]}/{[.AppName]}ctl:{APP_VERSION}"
  {[.AppName]}ctl:
    image: ${REGISTRY_PREFIX}/${APP_NAME}ctl:${APP_VERSION}
    container_name: ${APP_NAME}ctl
    restart: "no"
    platform: ${IMAGE_PLATFORM}
    build:
      context: ../../
      dockerfile: build/docker/{[.AppName]}ctl/Dockerfile
    networks:
      - {[.AppName]}
    volumes:
      - ${DATA_PATH_HOST}/config:/etc/{[.AppName]}
      - ${DATA_PATH_HOST}/log/{[.AppName]}ctl:/opt/{[.AppName]}/storage/log

  promtail:
    image: grafana/promtail
    container_name: ${APP_NAME}-promtail
    restart: always
    platform: ${IMAGE_PLATFORM}
    hostname: promtail
    user: root
    networks:
      - {[.AppName]}
    volumes:
      - ${DATA_PATH_HOST}/config/promtail.yaml:/etc/promtail/promtail.yaml
      - ${DATA_PATH_HOST}/data/promtail:/promtail
      - ${DATA_PATH_HOST}/log:/var/log/{[.AppName]}
    command:
      - "-config.file=/etc/promtail/promtail.yaml"

  mysql:
    image: mysql
    container_name: ${APP_NAME}-mysql
    restart: always
    platform: ${IMAGE_PLATFORM}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - {[.AppName]}
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/data/mysql:/var/lib/mysql

  redis:
    image: redis
    container_name: ${APP_NAME}-redis
    restart: always
    platform: ${IMAGE_PLATFORM}
    networks:
      - {[.AppName]}
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - ${DATA_PATH_HOST}/data/redis:/data
